version: '3'
services:
  node:
    image: node:17.8-alpine3.14
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
    ports:
      - 3000:3000
    environment:
      - TWITTER_APP_KEY=
      - TWITTER_APP_SECRET=
      - TWITTER_ACCESS_TOKEN=
      - TWITTER_ACCESS_SECRET=
      - NOTION_TOKEN=