name: tweet latest stats

on:
  schedule:
    - cron:  '45 6 * * *'
  workflow_dispatch:
jobs:
  tweet:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17
    
    - name: tweet stats
      env:
        TWITTER_APP_KEY: ${{secrets.TWITTER_APP_KEY}}
        TWITTER_APP_SECRET: ${{secrets.TWITTER_APP_SECRET}}
        TWITTER_ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
        TWITTER_ACCESS_SECRET: ${{secrets.TWITTER_ACCESS_SECRET}}
      run: |
        npm install
        npx ts-node --files ./src/tweet.ts
